### PR TITLE
Add opa-middleware in third-party middleware section

### PR DESCRIPTION
**Pull request by Joffref**

### CODE REVIEW

**Comment by ReneWerner87** [comment]
what is the different to our https://github.com/gofiber/contrib/tree/main/opafiber middleware ?

**Comment by Joffref** [comment]
Two important things :

- firstly, in the contrib plugin you can only use a local provided policy whereas with this one you can query a remote OPA instance.

- secondly, in the contrib plugin you can't modify the input payload for OPA, meaning that you policy must evaluate only the request path and method because it's hard coded like this. Whereas with this one you can add any input you want. It gives more flexibility.

**Comment by ReneWerner87** [comment]
ok thx for the explanation
maybe we can improve our middleware and then there is no need for a second one 

@mstrYoda what do you think ?

**Comment by Joffref** [comment]
If you have any question about the implementation I made or if you want to use it don't hesitate to ping me :+1:

**Comment by mstrYoda** [comment]
> ok thx for the explanation maybe we can improve our middleware and then there is no need for a second one
> 
> @mstrYoda what do you think ?

Well, there are quite similarities between the code written by @Joffref and our current OPA middleware. Especially the namings, and approach to use rego.

I could not understand why to reimplement the same logic and almost the same code instead of contributing to the existing one. Even the namings are the same, that looks quite weird to me.

Also, the new functionality is not related to OPA. It is actually a "sending HTTP request middleware". Maybe this one can be another middleware?

Of course, diversity/variety is a good thing. But, I think we should also consider not splitting the effort and package usage.

**Comment by Joffref** [comment]
> Well, there are quite similarities between the code written by @Joffref and our current OPA middleware. Especially the namings, and approach to use rego.

Hey @mstrYoda, what do you mean about similarities ? After a quick look at your middleware, both are quite different. About Rego approach, yes it's similar because OPA works like this.

> I could not understand why to reimplement the same logic and almost the same code instead of contributing to the existing one. Even the namings are the same, that looks quite weird to me.

My package provides not only a fiber middleware but also (ATM) a gin and a HTTP middleware. 

> Also, the new functionality is not related to OPA. It is actually a "sending HTTP request middleware". Maybe this one can be another middleware?

I don't thinks it's only a "sending HTTP request middleware" but a requested feature : As an OPA user I would like to be able to resolve policies request locally or remotely in the same manner.

**Pull request merged**
