### PR TITLE
Added alpody/golang-fiber-realworld-example-app to Recipes

### PR DESCRIPTION
**Pull request by alpody**

### CODE REVIEW

**Comment by gaby** [comment]
@alpody Before merging this, can you update that repo? 

- Add support for dependabot to track Fiber updates
- The go.mod should point to 1.18 min
- Update all the Fiber middlewares
- Pull the 7 commits from upstream
- The jwt middleware is now under github.com/gofiber/contrib/jwt

Thanks!

**Comment by ReneWerner87** [comment]
@alpody can you improve your repository and work through gaby's task list

**Comment by ReneWerner87** [comment]
@alpody can you improve your repository and work through gaby's task list

**Comment by alpody** [comment]
> @alpody can you improve your repository and work through gaby's task list

Yes, I can

**Comment by alpody** [comment]
@gaby I've done task list

**Review by efectn — APPROVED** [review]

**Pull request merged**
